"""Curated facts for the Sun, planets, IAU dwarf planets, dwarf-planet candidates,
and planet ring systems.

Numeric values are from the NASA Planetary Fact Sheets
(https://nssdc.gsfc.nasa.gov/planetary/factsheet/) and JPL Solar System Dynamics
small-body / planetary fact sheets. Orbital elements at J2000 epoch
(JD 2451545.0) heliocentric; magnitudes / albedos at conventional reference.

These rarely change; the nightly refresh only re-pulls element / property
fields it can verify against upstream. The list itself is stable.
"""
from __future__ import annotations

# --------------------------------------------------------------------------
# The Sun
# --------------------------------------------------------------------------
SUN = {
    "id": "sun", "name": "Sun", "designation": "Sol",
    "wikipedia_url": "https://en.wikipedia.org/wiki/Sun",
    "physical": {"radius_km": 695700.0, "mass_kg": 1.98892e30,
                 "density_g_cm3": 1.408, "rotation_period_hours": 609.12,
                 "surface_gravity_m_s2": 274.0, "escape_velocity_km_s": 617.7,
                 "axial_tilt_deg": 7.25},
    "visual": {"absolute_magnitude_h": 4.83, "dominant_colour_hex": "#FFF4E5",
               "spectral_type": "G2V"},
}

# --------------------------------------------------------------------------
# Planets
#   semi_major_axis_au, eccentricity, inclination_deg, longitude_ascending_node_deg,
#   argument_periapsis_deg, mean_anomaly_deg, orbital_period_days
#   Source: NASA planetary fact sheets + JPL keplerian elements (J2000).
# --------------------------------------------------------------------------
PLANETS = [
    {
        "id": "planet-mercury", "name": "Mercury",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Mercury_(planet)",
        "orbital": {"semi_major_axis_au": 0.38709927, "eccentricity": 0.20563593,
                    "inclination_deg": 7.00497902, "longitude_ascending_node_deg": 48.33076593,
                    "argument_periapsis_deg": 29.124, "mean_anomaly_deg": 174.79252722,
                    "orbital_period_days": 87.969, "perihelion_au": 0.307499,
                    "aphelion_au": 0.466697},
        "physical": {"radius_km": 2439.7, "mass_kg": 3.3011e23, "density_g_cm3": 5.427,
                     "rotation_period_hours": 1407.6, "axial_tilt_deg": 0.034,
                     "surface_gravity_m_s2": 3.7, "escape_velocity_km_s": 4.25},
        "visual": {"geometric_albedo": 0.142, "bond_albedo": 0.088,
                   "dominant_colour_hex": "#8C7853"},
    },
    {
        "id": "planet-venus", "name": "Venus",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Venus",
        "orbital": {"semi_major_axis_au": 0.72333566, "eccentricity": 0.00677672,
                    "inclination_deg": 3.39467605, "longitude_ascending_node_deg": 76.679843,
                    "argument_periapsis_deg": 54.884, "mean_anomaly_deg": 50.115,
                    "orbital_period_days": 224.701, "perihelion_au": 0.71843,
                    "aphelion_au": 0.72823},
        "physical": {"radius_km": 6051.8, "mass_kg": 4.8675e24, "density_g_cm3": 5.243,
                     "rotation_period_hours": -5832.5, "axial_tilt_deg": 177.36,
                     "surface_gravity_m_s2": 8.87, "escape_velocity_km_s": 10.36},
        "visual": {"geometric_albedo": 0.689, "bond_albedo": 0.76,
                   "dominant_colour_hex": "#E8B873"},
    },
    {
        "id": "planet-earth", "name": "Earth",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Earth",
        "orbital": {"semi_major_axis_au": 1.00000261, "eccentricity": 0.01671123,
                    "inclination_deg": -0.00001531, "longitude_ascending_node_deg": 0.0,
                    "argument_periapsis_deg": 102.937, "mean_anomaly_deg": 358.617,
                    "orbital_period_days": 365.256, "perihelion_au": 0.98329,
                    "aphelion_au": 1.01671},
        "physical": {"radius_km": 6371.0, "equatorial_radius_km": 6378.137,
                     "polar_radius_km": 6356.752, "mass_kg": 5.97237e24,
                     "density_g_cm3": 5.514, "rotation_period_hours": 23.9345,
                     "axial_tilt_deg": 23.4392811, "surface_gravity_m_s2": 9.80665,
                     "escape_velocity_km_s": 11.186},
        "visual": {"geometric_albedo": 0.434, "bond_albedo": 0.306,
                   "dominant_colour_hex": "#4F86C7"},
    },
    {
        "id": "planet-mars", "name": "Mars",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Mars",
        "orbital": {"semi_major_axis_au": 1.52371034, "eccentricity": 0.09339410,
                    "inclination_deg": 1.84969142, "longitude_ascending_node_deg": 49.55953891,
                    "argument_periapsis_deg": 286.502, "mean_anomaly_deg": 19.412,
                    "orbital_period_days": 686.980, "perihelion_au": 1.38133,
                    "aphelion_au": 1.66608},
        "physical": {"radius_km": 3389.5, "equatorial_radius_km": 3396.2,
                     "polar_radius_km": 3376.2, "mass_kg": 6.4171e23,
                     "density_g_cm3": 3.9335, "rotation_period_hours": 24.6229,
                     "axial_tilt_deg": 25.19, "surface_gravity_m_s2": 3.71,
                     "escape_velocity_km_s": 5.03},
        "visual": {"geometric_albedo": 0.170, "bond_albedo": 0.25,
                   "dominant_colour_hex": "#C1440E"},
    },
    {
        "id": "planet-jupiter", "name": "Jupiter",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Jupiter",
        "orbital": {"semi_major_axis_au": 5.20288700, "eccentricity": 0.04838624,
                    "inclination_deg": 1.30439695, "longitude_ascending_node_deg": 100.47390909,
                    "argument_periapsis_deg": 273.867, "mean_anomaly_deg": 20.020,
                    "orbital_period_days": 4332.589, "perihelion_au": 4.95029,
                    "aphelion_au": 5.45492},
        "physical": {"radius_km": 69911.0, "equatorial_radius_km": 71492.0,
                     "polar_radius_km": 66854.0, "mass_kg": 1.8982e27,
                     "density_g_cm3": 1.326, "rotation_period_hours": 9.9250,
                     "axial_tilt_deg": 3.13, "surface_gravity_m_s2": 24.79,
                     "escape_velocity_km_s": 59.5},
        "visual": {"geometric_albedo": 0.538, "bond_albedo": 0.503,
                   "dominant_colour_hex": "#D8CA9D"},
    },
    {
        "id": "planet-saturn", "name": "Saturn",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Saturn",
        "orbital": {"semi_major_axis_au": 9.53667594, "eccentricity": 0.05386179,
                    "inclination_deg": 2.48599187, "longitude_ascending_node_deg": 113.66242448,
                    "argument_periapsis_deg": 339.392, "mean_anomaly_deg": 317.020,
                    "orbital_period_days": 10759.22, "perihelion_au": 9.04108,
                    "aphelion_au": 10.1238},
        "physical": {"radius_km": 58232.0, "equatorial_radius_km": 60268.0,
                     "polar_radius_km": 54364.0, "mass_kg": 5.6834e26,
                     "density_g_cm3": 0.687, "rotation_period_hours": 10.656,
                     "axial_tilt_deg": 26.73, "surface_gravity_m_s2": 10.44,
                     "escape_velocity_km_s": 35.5},
        "visual": {"geometric_albedo": 0.499, "bond_albedo": 0.342,
                   "dominant_colour_hex": "#EAD6A0"},
    },
    {
        "id": "planet-uranus", "name": "Uranus",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Uranus",
        "discoverer": "William Herschel", "discovery_date": "1781-03-13",
        "orbital": {"semi_major_axis_au": 19.18916464, "eccentricity": 0.04725744,
                    "inclination_deg": 0.77263783, "longitude_ascending_node_deg": 74.01692503,
                    "argument_periapsis_deg": 96.998857, "mean_anomaly_deg": 142.238600,
                    "orbital_period_days": 30688.5, "perihelion_au": 18.286,
                    "aphelion_au": 20.0965},
        "physical": {"radius_km": 25362.0, "equatorial_radius_km": 25559.0,
                     "polar_radius_km": 24973.0, "mass_kg": 8.6810e25,
                     "density_g_cm3": 1.27, "rotation_period_hours": -17.24,
                     "axial_tilt_deg": 97.77, "surface_gravity_m_s2": 8.69,
                     "escape_velocity_km_s": 21.3},
        "visual": {"geometric_albedo": 0.488, "bond_albedo": 0.300,
                   "dominant_colour_hex": "#A9D7E3"},
    },
    {
        "id": "planet-neptune", "name": "Neptune",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Neptune",
        "discoverer": "Urbain Le Verrier, Johann Galle, Heinrich d'Arrest",
        "discovery_date": "1846-09-23",
        "orbital": {"semi_major_axis_au": 30.06992276, "eccentricity": 0.00859048,
                    "inclination_deg": 1.77004347, "longitude_ascending_node_deg": 131.78422574,
                    "argument_periapsis_deg": 276.336, "mean_anomaly_deg": 256.228,
                    "orbital_period_days": 60182.0, "perihelion_au": 29.81079,
                    "aphelion_au": 30.32706},
        "physical": {"radius_km": 24622.0, "equatorial_radius_km": 24764.0,
                     "polar_radius_km": 24341.0, "mass_kg": 1.02413e26,
                     "density_g_cm3": 1.638, "rotation_period_hours": 16.11,
                     "axial_tilt_deg": 28.32, "surface_gravity_m_s2": 11.15,
                     "escape_velocity_km_s": 23.5},
        "visual": {"geometric_albedo": 0.442, "bond_albedo": 0.290,
                   "dominant_colour_hex": "#3F5BAA"},
    },
]

# --------------------------------------------------------------------------
# IAU-recognised dwarf planets (5) + ~5–10 candidates.
# --------------------------------------------------------------------------
DWARF_PLANETS = [
    {"id": "dwarf-ceres", "name": "Ceres", "designation": "(1) Ceres",
     "object_type": "dwarf_planet", "discoverer": "Giuseppe Piazzi",
     "discovery_date": "1801-01-01",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Ceres_(dwarf_planet)",
     "spkid": 2000001,
     "physical": {"radius_km": 469.73, "mass_kg": 9.3835e20, "density_g_cm3": 2.162,
                  "rotation_period_hours": 9.074170, "surface_gravity_m_s2": 0.27,
                  "escape_velocity_km_s": 0.51, "axial_tilt_deg": 4.0},
     "visual": {"geometric_albedo": 0.09, "absolute_magnitude_h": 3.34,
                "dominant_colour_hex": "#A6A6A0"}},
    {"id": "dwarf-pluto", "name": "Pluto", "designation": "(134340) Pluto",
     "object_type": "dwarf_planet", "discoverer": "Clyde Tombaugh",
     "discovery_date": "1930-02-18",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Pluto",
     "spkid": 999,
     "physical": {"radius_km": 1188.3, "mass_kg": 1.303e22, "density_g_cm3": 1.854,
                  "rotation_period_hours": -153.2928, "axial_tilt_deg": 119.591,
                  "surface_gravity_m_s2": 0.62, "escape_velocity_km_s": 1.21},
     "visual": {"geometric_albedo": 0.52, "absolute_magnitude_h": -0.7,
                "dominant_colour_hex": "#CFA88B"}},
    {"id": "dwarf-eris", "name": "Eris", "designation": "(136199) Eris",
     "object_type": "dwarf_planet",
     "discoverer": "M. Brown, C. Trujillo, D. Rabinowitz",
     "discovery_date": "2005-01-05",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Eris_(dwarf_planet)",
     "spkid": 2136199,
     "physical": {"radius_km": 1163.0, "mass_kg": 1.6466e22, "density_g_cm3": 2.43,
                  "rotation_period_hours": 378.0, "surface_gravity_m_s2": 0.82,
                  "escape_velocity_km_s": 1.38},
     "visual": {"geometric_albedo": 0.96, "absolute_magnitude_h": -1.21,
                "dominant_colour_hex": "#D8D6CF"}},
    {"id": "dwarf-makemake", "name": "Makemake", "designation": "(136472) Makemake",
     "object_type": "dwarf_planet",
     "discoverer": "M. Brown, C. Trujillo, D. Rabinowitz",
     "discovery_date": "2005-03-31",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Makemake",
     "spkid": 2136472,
     "physical": {"radius_km": 715.0, "mass_kg": 3.1e21, "density_g_cm3": 2.1,
                  "rotation_period_hours": 22.83},
     "visual": {"geometric_albedo": 0.82, "absolute_magnitude_h": -0.12,
                "dominant_colour_hex": "#B57F5B"}},
    {"id": "dwarf-haumea", "name": "Haumea", "designation": "(136108) Haumea",
     "object_type": "dwarf_planet",
     "discoverer": "M. Brown / J.L. Ortiz (disputed)",
     "discovery_date": "2004-12-28",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Haumea",
     "spkid": 2136108,
     "physical": {"radius_km": 780.0, "mass_kg": 4.006e21, "density_g_cm3": 1.885,
                  "rotation_period_hours": 3.9155},
     "visual": {"geometric_albedo": 0.51, "absolute_magnitude_h": 0.43,
                "dominant_colour_hex": "#C7C0B8"}},

    # Candidates
    {"id": "dwarf-orcus", "name": "Orcus", "designation": "(90482) Orcus",
     "object_type": "dwarf_planet_candidate",
     "discoverer": "M. Brown, C. Trujillo, D. Rabinowitz",
     "discovery_date": "2004-02-17",
     "wikipedia_url": "https://en.wikipedia.org/wiki/90482_Orcus",
     "spkid": 2090482,
     "physical": {"radius_km": 458.5, "mass_kg": 6.348e20},
     "visual": {"geometric_albedo": 0.231, "absolute_magnitude_h": 2.31}},
    {"id": "dwarf-quaoar", "name": "Quaoar", "designation": "(50000) Quaoar",
     "object_type": "dwarf_planet_candidate",
     "discoverer": "Chad Trujillo, Michael E. Brown",
     "discovery_date": "2002-06-04",
     "wikipedia_url": "https://en.wikipedia.org/wiki/50000_Quaoar",
     "spkid": 2050000,
     "physical": {"radius_km": 545.0, "mass_kg": 1.2e21},
     "visual": {"geometric_albedo": 0.124, "absolute_magnitude_h": 2.4}},
    {"id": "dwarf-sedna", "name": "Sedna", "designation": "(90377) Sedna",
     "object_type": "dwarf_planet_candidate",
     "discoverer": "M. Brown, C. Trujillo, D. Rabinowitz",
     "discovery_date": "2003-11-14",
     "wikipedia_url": "https://en.wikipedia.org/wiki/90377_Sedna",
     "spkid": 2090377,
     "physical": {"radius_km": 498.0},
     "visual": {"geometric_albedo": 0.32, "absolute_magnitude_h": 1.83,
                "dominant_colour_hex": "#A0383E"}},
    {"id": "dwarf-gonggong", "name": "Gonggong", "designation": "(225088) Gonggong",
     "object_type": "dwarf_planet_candidate",
     "discoverer": "M. Schwamb, M. Brown, D. Rabinowitz",
     "discovery_date": "2007-07-17",
     "wikipedia_url": "https://en.wikipedia.org/wiki/225088_Gonggong",
     "spkid": 2225088,
     "physical": {"radius_km": 615.0, "mass_kg": 1.75e21},
     "visual": {"geometric_albedo": 0.14, "absolute_magnitude_h": 1.85}},
    {"id": "dwarf-salacia", "name": "Salacia", "designation": "(120347) Salacia",
     "object_type": "dwarf_planet_candidate",
     "discoverer": "H. Roe, M. Brown, K. Bauer",
     "discovery_date": "2004-09-22",
     "wikipedia_url": "https://en.wikipedia.org/wiki/120347_Salacia",
     "spkid": 2120347,
     "physical": {"radius_km": 423.0, "mass_kg": 4.92e20},
     "visual": {"geometric_albedo": 0.044, "absolute_magnitude_h": 4.25}},
]

# --------------------------------------------------------------------------
# Moons. We keep this list curated for the major / notable moons (covers the
# parents you care about for modelling: Mars 2, Jupiter ≥90, Saturn ≥140,
# Uranus 28, Neptune 16, Pluto 5, plus dwarf-planet moons). populate_initial
# also augments via JPL's natural satellites list for completeness.
#
# This module just declares the curated subset with rich physical data; the
# script supplements with the full IAU list when fetching SBDB / Horizons.
# --------------------------------------------------------------------------

# Earth
EARTH_MOONS = [
    {"id": "moon-luna", "name": "Moon", "designation": "Luna",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Moon",
     "physical": {"radius_km": 1737.4, "mass_kg": 7.342e22, "density_g_cm3": 3.344,
                  "rotation_period_hours": 655.728, "surface_gravity_m_s2": 1.62,
                  "escape_velocity_km_s": 2.38, "axial_tilt_deg": 6.687},
     "orbital": {"semi_major_axis_au": 0.00257, "eccentricity": 0.0549,
                 "inclination_deg": 5.145, "orbital_period_days": 27.321661},
     "visual": {"geometric_albedo": 0.136, "bond_albedo": 0.11,
                "dominant_colour_hex": "#C9C9C9"}},
]

# Mars
MARS_MOONS = [
    {"id": "moon-phobos", "name": "Phobos", "discoverer": "Asaph Hall",
     "discovery_date": "1877-08-18",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Phobos_(moon)",
     "physical": {"radius_km": 11.2667, "mass_kg": 1.0659e16, "density_g_cm3": 1.876,
                  "rotation_period_hours": 7.65},
     "orbital": {"semi_major_axis_au": 6.268e-5, "eccentricity": 0.0151,
                 "inclination_deg": 1.093, "orbital_period_days": 0.31891023},
     "visual": {"geometric_albedo": 0.071, "dominant_colour_hex": "#7A6A5F"}},
    {"id": "moon-deimos", "name": "Deimos", "discoverer": "Asaph Hall",
     "discovery_date": "1877-08-12",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Deimos_(moon)",
     "physical": {"radius_km": 6.2, "mass_kg": 1.4762e15, "density_g_cm3": 1.471,
                  "rotation_period_hours": 30.312},
     "orbital": {"semi_major_axis_au": 1.5674e-4, "eccentricity": 0.00033,
                 "inclination_deg": 0.93, "orbital_period_days": 1.263},
     "visual": {"geometric_albedo": 0.068, "dominant_colour_hex": "#9A8D80"}},
]

# Jupiter — Galileans + named irregulars (subset of curated detail; the rest
# come from the satellites list).
JUPITER_GALILEAN = [
    {"id": "moon-io", "name": "Io", "discoverer": "Galileo Galilei",
     "discovery_date": "1610-01-08",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Io_(moon)",
     "physical": {"radius_km": 1821.6, "mass_kg": 8.9319e22, "density_g_cm3": 3.528,
                  "rotation_period_hours": 42.4582, "surface_gravity_m_s2": 1.796},
     "orbital": {"semi_major_axis_au": 2.8181e-3, "eccentricity": 0.0041,
                 "inclination_deg": 0.05, "orbital_period_days": 1.769137786},
     "visual": {"geometric_albedo": 0.63, "dominant_colour_hex": "#E3D27E"}},
    {"id": "moon-europa", "name": "Europa", "discoverer": "Galileo Galilei",
     "discovery_date": "1610-01-08",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Europa_(moon)",
     "physical": {"radius_km": 1560.8, "mass_kg": 4.7998e22, "density_g_cm3": 3.013,
                  "rotation_period_hours": 85.2244, "surface_gravity_m_s2": 1.314},
     "orbital": {"semi_major_axis_au": 4.4860e-3, "eccentricity": 0.009,
                 "inclination_deg": 0.47, "orbital_period_days": 3.551181},
     "visual": {"geometric_albedo": 0.67, "dominant_colour_hex": "#B79A78"}},
    {"id": "moon-ganymede", "name": "Ganymede", "discoverer": "Galileo Galilei",
     "discovery_date": "1610-01-07",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Ganymede_(moon)",
     "physical": {"radius_km": 2634.1, "mass_kg": 1.4819e23, "density_g_cm3": 1.936,
                  "rotation_period_hours": 171.71, "surface_gravity_m_s2": 1.428},
     "orbital": {"semi_major_axis_au": 7.1551e-3, "eccentricity": 0.0013,
                 "inclination_deg": 0.20, "orbital_period_days": 7.15455},
     "visual": {"geometric_albedo": 0.43, "dominant_colour_hex": "#928677"}},
    {"id": "moon-callisto", "name": "Callisto", "discoverer": "Galileo Galilei",
     "discovery_date": "1610-01-07",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Callisto_(moon)",
     "physical": {"radius_km": 2410.3, "mass_kg": 1.0759e23, "density_g_cm3": 1.834,
                  "rotation_period_hours": 400.5359, "surface_gravity_m_s2": 1.235},
     "orbital": {"semi_major_axis_au": 1.25887e-2, "eccentricity": 0.0074,
                 "inclination_deg": 0.192, "orbital_period_days": 16.6890184},
     "visual": {"geometric_albedo": 0.22, "dominant_colour_hex": "#5C4F40"}},
]

# Saturn — major named moons
SATURN_MAJOR = [
    {"id": "moon-titan", "name": "Titan", "discoverer": "Christiaan Huygens",
     "discovery_date": "1655-03-25",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Titan_(moon)",
     "physical": {"radius_km": 2574.7, "mass_kg": 1.3452e23, "density_g_cm3": 1.879,
                  "rotation_period_hours": 382.69, "surface_gravity_m_s2": 1.352},
     "orbital": {"semi_major_axis_au": 8.1681e-3, "eccentricity": 0.0288,
                 "inclination_deg": 0.34854, "orbital_period_days": 15.945},
     "visual": {"geometric_albedo": 0.22, "dominant_colour_hex": "#D9A05B"}},
    {"id": "moon-enceladus", "name": "Enceladus", "discoverer": "William Herschel",
     "discovery_date": "1789-08-28",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Enceladus",
     "physical": {"radius_km": 252.1, "mass_kg": 1.08022e20, "density_g_cm3": 1.609,
                  "rotation_period_hours": 32.9, "surface_gravity_m_s2": 0.113},
     "orbital": {"semi_major_axis_au": 1.591e-3, "eccentricity": 0.0047,
                 "inclination_deg": 0.009, "orbital_period_days": 1.370218},
     "visual": {"geometric_albedo": 0.99, "dominant_colour_hex": "#EFEFEF"}},
    {"id": "moon-mimas", "name": "Mimas", "discoverer": "William Herschel",
     "discovery_date": "1789-09-17",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Mimas_(moon)",
     "physical": {"radius_km": 198.2, "mass_kg": 3.7493e19, "density_g_cm3": 1.148},
     "orbital": {"semi_major_axis_au": 1.241e-3, "eccentricity": 0.0202,
                 "orbital_period_days": 0.942422},
     "visual": {"geometric_albedo": 0.962}},
    {"id": "moon-tethys", "name": "Tethys", "discoverer": "Giovanni Cassini",
     "discovery_date": "1684-03-21",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Tethys_(moon)",
     "physical": {"radius_km": 531.1, "mass_kg": 6.17449e20, "density_g_cm3": 0.984},
     "orbital": {"semi_major_axis_au": 1.967e-3, "eccentricity": 0.0001,
                 "orbital_period_days": 1.887802},
     "visual": {"geometric_albedo": 1.229}},
    {"id": "moon-dione", "name": "Dione", "discoverer": "Giovanni Cassini",
     "discovery_date": "1684-03-21",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Dione_(moon)",
     "physical": {"radius_km": 561.4, "mass_kg": 1.0954845e21, "density_g_cm3": 1.478},
     "orbital": {"semi_major_axis_au": 2.522e-3, "eccentricity": 0.0022,
                 "orbital_period_days": 2.736915},
     "visual": {"geometric_albedo": 0.998}},
    {"id": "moon-rhea", "name": "Rhea", "discoverer": "Giovanni Cassini",
     "discovery_date": "1672-12-23",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Rhea_(moon)",
     "physical": {"radius_km": 763.8, "mass_kg": 2.306518e21, "density_g_cm3": 1.236},
     "orbital": {"semi_major_axis_au": 3.524e-3, "eccentricity": 0.001258,
                 "orbital_period_days": 4.518212},
     "visual": {"geometric_albedo": 0.949}},
    {"id": "moon-iapetus", "name": "Iapetus", "discoverer": "Giovanni Cassini",
     "discovery_date": "1671-10-25",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Iapetus_(moon)",
     "physical": {"radius_km": 734.5, "mass_kg": 1.805635e21, "density_g_cm3": 1.088},
     "orbital": {"semi_major_axis_au": 2.380e-2, "eccentricity": 0.0286125,
                 "inclination_deg": 15.47, "orbital_period_days": 79.3215},
     "visual": {"geometric_albedo": 0.05}},
    {"id": "moon-phoebe", "name": "Phoebe", "discoverer": "William Henry Pickering",
     "discovery_date": "1899-03-18",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Phoebe_(moon)",
     "physical": {"radius_km": 106.5, "mass_kg": 8.292e18, "density_g_cm3": 1.638},
     "orbital": {"semi_major_axis_au": 8.6480e-2, "eccentricity": 0.156242,
                 "inclination_deg": 175.243, "orbital_period_days": 550.31},
     "visual": {"geometric_albedo": 0.06}},
    {"id": "moon-hyperion", "name": "Hyperion",
     "discoverer": "Bond, Bond, Lassell", "discovery_date": "1848-09-16",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Hyperion_(moon)",
     "physical": {"radius_km": 135.0, "mass_kg": 5.6199e18},
     "orbital": {"semi_major_axis_au": 9.9255e-3, "eccentricity": 0.1230061,
                 "orbital_period_days": 21.2766088},
     "visual": {"geometric_albedo": 0.3}},
]

# Uranus moons
URANUS_MAJOR = [
    {"id": "moon-miranda", "name": "Miranda", "discoverer": "Gerard Kuiper",
     "discovery_date": "1948-02-16",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Miranda_(moon)",
     "physical": {"radius_km": 235.8, "mass_kg": 6.4e19},
     "orbital": {"semi_major_axis_au": 8.6692e-4, "eccentricity": 0.0013,
                 "inclination_deg": 4.232, "orbital_period_days": 1.413479}},
    {"id": "moon-ariel", "name": "Ariel", "discoverer": "William Lassell",
     "discovery_date": "1851-10-24",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Ariel_(moon)",
     "physical": {"radius_km": 578.9, "mass_kg": 1.251e21},
     "orbital": {"semi_major_axis_au": 1.27636e-3, "eccentricity": 0.0012,
                 "orbital_period_days": 2.520}},
    {"id": "moon-umbriel", "name": "Umbriel", "discoverer": "William Lassell",
     "discovery_date": "1851-10-24",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Umbriel_(moon)",
     "physical": {"radius_km": 584.7, "mass_kg": 1.275e21},
     "orbital": {"semi_major_axis_au": 1.77810e-3, "eccentricity": 0.0039,
                 "orbital_period_days": 4.144}},
    {"id": "moon-titania", "name": "Titania", "discoverer": "William Herschel",
     "discovery_date": "1787-01-11",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Titania_(moon)",
     "physical": {"radius_km": 788.4, "mass_kg": 3.4e21},
     "orbital": {"semi_major_axis_au": 2.91465e-3, "eccentricity": 0.0011,
                 "orbital_period_days": 8.706}},
    {"id": "moon-oberon", "name": "Oberon", "discoverer": "William Herschel",
     "discovery_date": "1787-01-11",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Oberon_(moon)",
     "physical": {"radius_km": 761.4, "mass_kg": 3.076e21},
     "orbital": {"semi_major_axis_au": 3.89933e-3, "eccentricity": 0.0014,
                 "orbital_period_days": 13.463}},
]

# Neptune moons
NEPTUNE_MAJOR = [
    {"id": "moon-triton", "name": "Triton", "discoverer": "William Lassell",
     "discovery_date": "1846-10-10",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Triton_(moon)",
     "physical": {"radius_km": 1353.4, "mass_kg": 2.139e22, "density_g_cm3": 2.061,
                  "rotation_period_hours": 141.04},
     "orbital": {"semi_major_axis_au": 2.3711e-3, "eccentricity": 0.000016,
                 "inclination_deg": 156.865, "orbital_period_days": 5.8769},
     "visual": {"geometric_albedo": 0.76, "dominant_colour_hex": "#D6B58D"}},
    {"id": "moon-nereid", "name": "Nereid", "discoverer": "Gerard Kuiper",
     "discovery_date": "1949-05-01",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Nereid_(moon)",
     "physical": {"radius_km": 170.0, "mass_kg": 3.1e19},
     "orbital": {"semi_major_axis_au": 3.6857e-2, "eccentricity": 0.7507,
                 "inclination_deg": 7.090, "orbital_period_days": 360.13}},
]

# Pluto moons
PLUTO_MOONS = [
    {"id": "moon-charon", "name": "Charon", "discoverer": "James W. Christy",
     "discovery_date": "1978-06-22",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Charon_(moon)",
     "physical": {"radius_km": 606.0, "mass_kg": 1.586e21, "density_g_cm3": 1.702,
                  "rotation_period_hours": 153.2935},
     "orbital": {"semi_major_axis_au": 1.31e-4, "eccentricity": 0.00005,
                 "orbital_period_days": 6.3872304},
     "visual": {"geometric_albedo": 0.41}},
    {"id": "moon-nix", "name": "Nix",
     "discoverer": "Pluto Companion Search Team",
     "discovery_date": "2005-05-15",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Nix_(moon)",
     "physical": {"radius_km": 24.5}, "orbital": {"orbital_period_days": 24.85463}},
    {"id": "moon-hydra", "name": "Hydra",
     "discoverer": "Pluto Companion Search Team",
     "discovery_date": "2005-05-15",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Hydra_(moon)",
     "physical": {"radius_km": 25.0}, "orbital": {"orbital_period_days": 38.20177}},
    {"id": "moon-kerberos", "name": "Kerberos",
     "discoverer": "HST Pluto Companion Search Team",
     "discovery_date": "2011-06-28",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Kerberos_(moon)",
     "physical": {"radius_km": 6.0}, "orbital": {"orbital_period_days": 32.16756}},
    {"id": "moon-styx", "name": "Styx",
     "discoverer": "HST Pluto Companion Search Team",
     "discovery_date": "2012-07-07",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Styx_(moon)",
     "physical": {"radius_km": 5.0}, "orbital": {"orbital_period_days": 20.16155}},
]

# Other dwarf-planet moons
OTHER_DWARF_MOONS = [
    {"id": "moon-dysnomia", "name": "Dysnomia", "parent_id": "dwarf-eris",
     "discoverer": "Brown, Van Dam, Bouchez",
     "discovery_date": "2005-09-10",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Dysnomia_(moon)",
     "physical": {"radius_km": 350.0}, "orbital": {"orbital_period_days": 15.79}},
    {"id": "moon-hi-iaka", "name": "Hi'iaka", "parent_id": "dwarf-haumea",
     "discoverer": "Brown et al.", "discovery_date": "2005-01-26",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Hi%27iaka_(moon)",
     "physical": {"radius_km": 160.0}, "orbital": {"orbital_period_days": 49.12}},
    {"id": "moon-namaka", "name": "Namaka", "parent_id": "dwarf-haumea",
     "discoverer": "Brown et al.", "discovery_date": "2005-06-30",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Namaka_(moon)",
     "physical": {"radius_km": 85.0}, "orbital": {"orbital_period_days": 18.28}},
    {"id": "moon-mk2", "name": "MK2", "parent_id": "dwarf-makemake",
     "discoverer": "Parker, Buie et al.", "discovery_date": "2015-04-27",
     "wikipedia_url": "https://en.wikipedia.org/wiki/S/2015_(136472)_1",
     "physical": {"radius_km": 87.5}, "orbital": {"orbital_period_days": 12.4}},
    {"id": "moon-vanth", "name": "Vanth", "parent_id": "dwarf-orcus",
     "discoverer": "Brown, Suer", "discovery_date": "2005-11-13",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Vanth_(moon)",
     "physical": {"radius_km": 221.0}, "orbital": {"orbital_period_days": 9.5406}},
    {"id": "moon-weywot", "name": "Weywot", "parent_id": "dwarf-quaoar",
     "discoverer": "M.E. Brown, T.A. Suer",
     "discovery_date": "2007-02-22",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Weywot",
     "physical": {"radius_km": 81.0}, "orbital": {"orbital_period_days": 12.438}},
    {"id": "moon-xiangliu", "name": "Xiangliu", "parent_id": "dwarf-gonggong",
     "discoverer": "Kiss et al.", "discovery_date": "2010-01-08",
     "wikipedia_url": "https://en.wikipedia.org/wiki/Xiangliu_(moon)",
     "physical": {"radius_km": 50.0}, "orbital": {"orbital_period_days": 25.220}},
]

# --------------------------------------------------------------------------
# Ring systems
# --------------------------------------------------------------------------
RINGS = [
    # Jupiter
    {"parent_id": "planet-jupiter", "name": "Halo Ring",
     "inner_radius_km": 92000, "outer_radius_km": 122500, "thickness_km": 12500},
    {"parent_id": "planet-jupiter", "name": "Main Ring",
     "inner_radius_km": 122500, "outer_radius_km": 129000, "thickness_km": 30},
    {"parent_id": "planet-jupiter", "name": "Amalthea Gossamer Ring",
     "inner_radius_km": 129000, "outer_radius_km": 182000, "thickness_km": 2000},
    {"parent_id": "planet-jupiter", "name": "Thebe Gossamer Ring",
     "inner_radius_km": 129000, "outer_radius_km": 226000, "thickness_km": 8400},

    # Saturn
    {"parent_id": "planet-saturn", "name": "D Ring",
     "inner_radius_km": 66900, "outer_radius_km": 74510},
    {"parent_id": "planet-saturn", "name": "C Ring",
     "inner_radius_km": 74658, "outer_radius_km": 92000},
    {"parent_id": "planet-saturn", "name": "B Ring",
     "inner_radius_km": 92000, "outer_radius_km": 117580},
    {"parent_id": "planet-saturn", "name": "Cassini Division",
     "inner_radius_km": 117580, "outer_radius_km": 122170},
    {"parent_id": "planet-saturn", "name": "A Ring",
     "inner_radius_km": 122170, "outer_radius_km": 136775},
    {"parent_id": "planet-saturn", "name": "F Ring",
     "inner_radius_km": 140224, "outer_radius_km": 140324},
    {"parent_id": "planet-saturn", "name": "G Ring",
     "inner_radius_km": 166000, "outer_radius_km": 175000},
    {"parent_id": "planet-saturn", "name": "E Ring",
     "inner_radius_km": 180000, "outer_radius_km": 480000},
    {"parent_id": "planet-saturn", "name": "Phoebe Ring",
     "inner_radius_km": 7600000, "outer_radius_km": 16000000},

    # Uranus
    {"parent_id": "planet-uranus", "name": "Zeta Ring",
     "inner_radius_km": 32000, "outer_radius_km": 39600},
    {"parent_id": "planet-uranus", "name": "6 Ring",
     "inner_radius_km": 41837, "outer_radius_km": 41837},
    {"parent_id": "planet-uranus", "name": "5 Ring",
     "inner_radius_km": 42234, "outer_radius_km": 42234},
    {"parent_id": "planet-uranus", "name": "4 Ring",
     "inner_radius_km": 42570, "outer_radius_km": 42570},
    {"parent_id": "planet-uranus", "name": "Alpha Ring",
     "inner_radius_km": 44718, "outer_radius_km": 44718},
    {"parent_id": "planet-uranus", "name": "Beta Ring",
     "inner_radius_km": 45661, "outer_radius_km": 45661},
    {"parent_id": "planet-uranus", "name": "Eta Ring",
     "inner_radius_km": 47175, "outer_radius_km": 47175},
    {"parent_id": "planet-uranus", "name": "Gamma Ring",
     "inner_radius_km": 47627, "outer_radius_km": 47627},
    {"parent_id": "planet-uranus", "name": "Delta Ring",
     "inner_radius_km": 48300, "outer_radius_km": 48300},
    {"parent_id": "planet-uranus", "name": "Lambda Ring",
     "inner_radius_km": 50023, "outer_radius_km": 50023},
    {"parent_id": "planet-uranus", "name": "Epsilon Ring",
     "inner_radius_km": 51149, "outer_radius_km": 51149},
    {"parent_id": "planet-uranus", "name": "Nu Ring",
     "inner_radius_km": 66100, "outer_radius_km": 69900},
    {"parent_id": "planet-uranus", "name": "Mu Ring",
     "inner_radius_km": 86000, "outer_radius_km": 103000},

    # Neptune
    {"parent_id": "planet-neptune", "name": "Galle Ring",
     "inner_radius_km": 40900, "outer_radius_km": 42900},
    {"parent_id": "planet-neptune", "name": "Le Verrier Ring",
     "inner_radius_km": 53200, "outer_radius_km": 53200},
    {"parent_id": "planet-neptune", "name": "Lassell Ring",
     "inner_radius_km": 53200, "outer_radius_km": 57200},
    {"parent_id": "planet-neptune", "name": "Arago Ring",
     "inner_radius_km": 57200, "outer_radius_km": 57200},
    {"parent_id": "planet-neptune", "name": "Adams Ring",
     "inner_radius_km": 62930, "outer_radius_km": 62930},

    # Haumea
    {"parent_id": "dwarf-haumea", "name": "Haumea ring",
     "inner_radius_km": 2287, "outer_radius_km": 2357},
    # Chariklo (centaur) — added later if we have the object row
]

# --------------------------------------------------------------------------
# Notable named TNOs / KBOs / centaurs not already in the dwarf-planet list.
# --------------------------------------------------------------------------
NOTABLE_TNOS = [
    {"id": "tno-arrokoth", "name": "Arrokoth", "designation": "(486958) Arrokoth",
     "object_type": "tno", "spkid": 2486958,
     "discoverer": "Marc Buie, Hubble Space Telescope",
     "discovery_date": "2014-06-26",
     "wikipedia_url": "https://en.wikipedia.org/wiki/486958_Arrokoth"},
    {"id": "tno-varuna", "name": "Varuna", "designation": "(20000) Varuna",
     "object_type": "tno", "spkid": 2020000,
     "discoverer": "Robert McMillan", "discovery_date": "2000-11-28",
     "wikipedia_url": "https://en.wikipedia.org/wiki/20000_Varuna"},
    {"id": "tno-ixion", "name": "Ixion", "designation": "(28978) Ixion",
     "object_type": "tno", "spkid": 2028978,
     "discoverer": "Deep Ecliptic Survey", "discovery_date": "2001-05-22",
     "wikipedia_url": "https://en.wikipedia.org/wiki/28978_Ixion"},
    {"id": "tno-2002-aw197", "name": "2002 AW197", "designation": "(55565) 2002 AW197",
     "object_type": "tno", "spkid": 2055565,
     "wikipedia_url": "https://en.wikipedia.org/wiki/(55565)_2002_AW197"},
    {"id": "tno-2007-or10", "name": "Gonggong (alt)", "designation": "(225088) Gonggong",
     "object_type": "tno", "spkid": 2225088},  # cross-referenced
    {"id": "centaur-chiron", "name": "Chiron", "designation": "(2060) Chiron",
     "object_type": "centaur", "spkid": 2002060,
     "discoverer": "Charles Kowal", "discovery_date": "1977-11-01",
     "wikipedia_url": "https://en.wikipedia.org/wiki/2060_Chiron"},
    {"id": "centaur-chariklo", "name": "Chariklo", "designation": "(10199) Chariklo",
     "object_type": "centaur", "spkid": 2010199,
     "discoverer": "James V. Scotti", "discovery_date": "1997-02-15",
     "wikipedia_url": "https://en.wikipedia.org/wiki/10199_Chariklo"},
    {"id": "centaur-pholus", "name": "Pholus", "designation": "(5145) Pholus",
     "object_type": "centaur", "spkid": 2005145,
     "discoverer": "David L. Rabinowitz", "discovery_date": "1992-01-09",
     "wikipedia_url": "https://en.wikipedia.org/wiki/5145_Pholus"},
    {"id": "centaur-nessus", "name": "Nessus", "designation": "(7066) Nessus",
     "object_type": "centaur", "spkid": 2007066,
     "discoverer": "David L. Rabinowitz", "discovery_date": "1993-04-26",
     "wikipedia_url": "https://en.wikipedia.org/wiki/7066_Nessus"},
    {"id": "tno-ms4", "name": "2002 MS4", "designation": "(307261) 2002 MS4",
     "object_type": "tno", "spkid": 2307261,
     "wikipedia_url": "https://en.wikipedia.org/wiki/(307261)_2002_MS4"},
]

# --------------------------------------------------------------------------
# Named periodic comets — small notable set; SBDB augments to all named.
# --------------------------------------------------------------------------
NOTABLE_COMETS = [
    {"name": "Halley", "designation": "1P/Halley", "spk_label": "1P"},
    {"name": "Encke", "designation": "2P/Encke", "spk_label": "2P"},
    {"name": "Biela", "designation": "3D/Biela", "spk_label": "3D"},
    {"name": "Faye", "designation": "4P/Faye", "spk_label": "4P"},
    {"name": "Tempel 1", "designation": "9P/Tempel", "spk_label": "9P"},
    {"name": "Tempel 2", "designation": "10P/Tempel", "spk_label": "10P"},
    {"name": "Tempel-Tuttle", "designation": "55P/Tempel-Tuttle", "spk_label": "55P"},
    {"name": "Churyumov-Gerasimenko", "designation": "67P/Churyumov-Gerasimenko",
     "spk_label": "67P"},
    {"name": "Hartley 2", "designation": "103P/Hartley", "spk_label": "103P"},
    {"name": "Wild 2", "designation": "81P/Wild", "spk_label": "81P"},
    {"name": "Borrelly", "designation": "19P/Borrelly", "spk_label": "19P"},
    {"name": "Giacobini-Zinner", "designation": "21P/Giacobini-Zinner",
     "spk_label": "21P"},
    {"name": "Swift-Tuttle", "designation": "109P/Swift-Tuttle", "spk_label": "109P"},
    {"name": "Holmes", "designation": "17P/Holmes", "spk_label": "17P"},
]
